import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import { Clock3, Search, X, MapPin, Phone, ArrowLeft } from 'lucide-react';
import './style.css';

const url = import.meta.env.VITE_SUPABASE_URL;
const key = import.meta.env.VITE_SUPABASE_ANON_KEY;
const db = url && key ? createClient(url, key) : null;
type Establishment = { id:string; nome:string; slug:string; descricao:string; logo_url:string|null; capa_url:string|null; cor_principal:string; telefone:string|null; endereco:string|null; fuso:string; fechado_hoje:boolean; aviso:string|null; aviso_ativo:boolean; aviso_ate:string|null };
type Category = {id:string; nome:string; ordem:number};
type Product = {id:string; categoria_id:string; nome:string; descricao:string; preco_centavos:number; preco_promocional_centavos:number|null; foto_url:string|null; video_url:string|null; video_poster_url:string|null; altura_cm:number|null; largura_cm:number|null; comprimento_cm:number|null; peso_g:number|null; volume_ml:number|null; serve_pessoas:number|null; alergenos:string|null; ingredientes:string|null; combo_itens:string[]; selos:string[]; status:string; dias_disponiveis:number[]|null; inicio_disponibilidade:string|null; fim_disponibilidade:string|null; ordem:number};
type Slot = {dia_semana:number; abre:string; fecha:string};
type Exception = {data:string; fechado:boolean; abre:string|null; fecha:string|null};
const days=['domingo','segunda-feira','terça-feira','quarta-feira','quinta-feira','sexta-feira','sábado'];
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100);
function timeAt(zone:string){try { const parts=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()); const part=(name:string)=>parts.find(x=>x.type===name)?.value||''; return {day:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(part('weekday')),date:`${part('year')}-${part('month')}-${part('day')}`,time:`${part('hour')}:${part('minute')}`}; } catch {return {day:new Date().getDay(),date:new Date().toISOString().slice(0,10),time:new Date().toTimeString().slice(0,5)};} }
function App(){
 const slug=decodeURIComponent(location.pathname.split('/').filter(Boolean)[0]||'');
 const table=new URLSearchParams(location.search).get('mesa');
 const [shop,setShop]=useState<Establishment|null>(null),[categories,setCategories]=useState<Category[]>([]),[products,setProducts]=useState<Product[]>([]),[slots,setSlots]=useState<Slot[]>([]),[exceptions,setExceptions]=useState<Exception[]>([]),[query,setQuery]=useState(''),[selected,setSelected]=useState<Product|null>(null),[hours,setHours]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[clock,setClock]=useState(0);
 useEffect(()=>{const id=setInterval(()=>setClock(x=>x+1),60000);return()=>clearInterval(id)},[]);
 useEffect(()=>{if(!db){setError('Cardápio ainda não configurado.');setLoading(false);return} if(!slug){setError('Abra o QR code do estabelecimento para ver o cardápio.');setLoading(false);return} let disposed=false; async function load(){const client=db!;const result=await client.from('estabelecimentos').select('*').eq('slug',slug).maybeSingle();if(disposed)return;if(result.error||!result.data){setError('Estabelecimento não encontrado.');setLoading(false);return}const s=result.data as Establishment;setShop(s);const [c,p,h,e]=await Promise.all([client.from('categorias').select('id,nome,ordem').eq('estabelecimento_id',s.id).eq('visivel',true).order('ordem'),client.from('produtos').select('*').eq('estabelecimento_id',s.id).eq('status','ativo').order('ordem'),client.from('horarios').select('dia_semana,abre,fecha').eq('estabelecimento_id',s.id),client.from('excecoes_horario').select('data,fechado,abre,fecha').eq('estabelecimento_id',s.id)]);if(disposed)return;if([c,p,h,e].some(x=>x.error)){setError('Não foi possível carregar o cardápio. Tente novamente.')} else {setCategories(c.data||[]);setProducts(p.data||[]);setSlots(h.data||[]);setExceptions(e.data||[])}setLoading(false)}load();return()=>{disposed=true}},[slug]);
 const now=timeAt(shop?.fuso||'America/Sao_Paulo');void clock;
 const exception=exceptions.find(x=>x.data===now.date);
 const today=exception ? exception.fechado?[]:[{abre:exception.abre||'',fecha:exception.fecha||''}] : slots.filter(x=>x.dia_semana===now.day);
 const open=!!shop&&!shop.fechado_hoje&&today.some(x=>x.abre.slice(0,5)<=now.time&&x.fecha.slice(0,5)>now.time);
 const next=today.find(x=>x.abre.slice(0,5)>now.time)?.abre.slice(0,5) || [...Array(7)].map((_,i)=>({offset:i+1,slot:slots.find(s=>s.dia_semana===(now.day+i+1)%7)})).find(x=>x.slot)?.slot?.abre.slice(0,5);
 const visible=useMemo(()=>products.filter(p=>{const q=query.toLocaleLowerCase('pt-BR');return (`${p.nome} ${p.descricao}`).toLocaleLowerCase('pt-BR').includes(q)&&(!p.dias_disponiveis||p.dias_disponiveis.includes(now.day))&&(!p.inicio_disponibilidade||p.inicio_disponibilidade.slice(0,5)<=now.time)&&(!p.fim_disponibilidade||p.fim_disponibilidade.slice(0,5)>now.time)}),[products,query,now.day,now.time]);
 useEffect(()=>{if(shop){document.title=`Cardápio • ${shop.nome}`;document.querySelector('meta[name="description"]')?.setAttribute('content',shop.descricao||`Confira o cardápio de ${shop.nome}`)}},[shop]);
 if(loading)return <main className="state">Carregando cardápio…</main>;
 if(error)return <main className="state"><h1>Ops!</h1><p>{error}</p><button onClick={()=>location.reload()}>Tentar novamente</button></main>;
 if(!shop)return null;
 return <div className="app" style={{'--brand':shop.cor_principal} as React.CSSProperties}>
  <header className="hero" style={shop.capa_url?{backgroundImage:`linear-gradient(90deg,rgba(25,28,24,.89),rgba(25,28,24,.40)),url(${shop.capa_url})`}:{}}><div className="wrap hero-inner"><div className="identity">{shop.logo_url&&<img src={shop.logo_url} alt={`Logo ${shop.nome}`}/>}<div><span className="eyebrow">CARDÁPIO DIGITAL {table?`· MESA ${table}`:''}</span><h1>{shop.nome}</h1><p>{shop.descricao}</p></div></div></div></header>
  <section className="status wrap"><div><span className={`pill ${open?'on':'off'}`}>{open?'● Aberto agora':'● Fechado agora'}</span><span className="muted">{!open&&next?` Próxima abertura às ${next}`:' Faça sua escolha com calma'}</span></div><button className="link" onClick={()=>setHours(true)}><Clock3 size={17}/> Horários</button>{shop.aviso_ativo&&shop.aviso&&(!shop.aviso_ate||new Date(shop.aviso_ate)>new Date())&&<p className="notice">{shop.aviso}</p>}{!open&&<p className="closed">O cardápio está disponível para consulta. Pedidos indisponíveis no momento.</p>}</section>
  <div className="sticky"><div className="wrap"><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busque no cardápio" aria-label="Buscar produtos"/></label><nav aria-label="Categorias">{categories.filter(c=>visible.some(p=>p.categoria_id===c.id)).map(c=><a key={c.id} href={`#cat-${c.id}`}>{c.nome}</a>)}</nav></div></div>
  <main className="wrap content">{products.length===0?<div className="empty">{shop.logo_url&&<img src={shop.logo_url} alt=""/>}<h2>Cardápio em preparação</h2><p>{shop.nome} está preparando novidades para você.</p></div>:visible.length===0?<div className="empty"><h2>Nenhum resultado</h2><p>Tente buscar por outro nome ou ingrediente.</p></div>:categories.map(c=>{const items=visible.filter(p=>p.categoria_id===c.id);return items.length?<section key={c.id} id={`cat-${c.id}`} className="category"><h2>{c.nome}</h2><div className="grid">{items.map(p=><button key={p.id} className="card" onClick={()=>setSelected(p)}><div className="photo">{p.foto_url?<img loading="lazy" src={p.foto_url} alt={p.nome}/>:<span>Sem foto</span>}{p.video_url&&<span className="badge video">Ver em 3D</span>}</div><div className="card-body">{p.selos.length>0&&<span className="tag">{p.selos[0]}</span>}<h3>{p.nome}</h3><p>{p.descricao}</p><strong>{money(p.preco_promocional_centavos??p.preco_centavos)}</strong>{p.preco_promocional_centavos!=null&&<del>{money(p.preco_centavos)}</del>}</div></button>)}</div></section>:null})}</main>
  <footer className="footer wrap">{shop.endereco&&<span><MapPin size={16}/>{shop.endereco}</span>}{shop.telefone&&<a href={`tel:${shop.telefone}`}><Phone size={16}/>{shop.telefone}</a>}<small>Feito com PedeAUTO</small></footer>
  {hours&&<div className="overlay" onMouseDown={()=>setHours(false)}><section className="modal small" role="dialog" aria-modal="true" aria-label="Horários" onMouseDown={e=>e.stopPropagation()}><button className="close" aria-label="Fechar" onClick={()=>setHours(false)}><X/></button><h2>Horários de atendimento</h2>{days.map((d,i)=><p className="hour" key={d}><strong>{d}</strong><span>{slots.filter(x=>x.dia_semana===i).map(x=>`${x.abre.slice(0,5)}–${x.fecha.slice(0,5)}`).join(' · ')||'Fechado'}</span></p>)}</section></div>}
  {selected&&<div className="overlay" onMouseDown={()=>setSelected(null)}><article className="modal product-modal" role="dialog" aria-modal="true" aria-label={selected.nome} onMouseDown={e=>e.stopPropagation()}><button className="close" aria-label="Fechar" onClick={()=>setSelected(null)}><X/></button>{selected.video_url?<video src={selected.video_url} poster={selected.video_poster_url||selected.foto_url||undefined} muted loop autoPlay playsInline controls preload="none" onError={e=>{e.currentTarget.style.display='none';const sibling=e.currentTarget.nextElementSibling as HTMLElement|null;if(sibling)sibling.style.display='block'}}/>:null}{selected.foto_url&&<img className="detail-image" src={selected.foto_url} alt={selected.nome} style={selected.video_url?{display:'none'}:{}}/>}<div className="modal-body"><button className="back" onClick={()=>setSelected(null)}><ArrowLeft size={17}/> Voltar ao cardápio</button><h2>{selected.nome}</h2><strong className="price">{money(selected.preco_promocional_centavos??selected.preco_centavos)}</strong><p>{selected.descricao}</p>{selected.serve_pessoas&&<p>Serve {selected.serve_pessoas} {selected.serve_pessoas===1?'pessoa':'pessoas'}</p>}{selected.combo_itens.length>0&&<><h3>O que inclui</h3><ul>{selected.combo_itens.map(x=><li key={x}>{x}</li>)}</ul></>}{[selected.altura_cm,selected.largura_cm,selected.comprimento_cm,selected.peso_g,selected.volume_ml].some(Boolean)&&<><h3>Medidas informadas pelo estabelecimento</h3><p>{[selected.altura_cm&&`Altura: ${selected.altura_cm} cm`,selected.largura_cm&&`Largura: ${selected.largura_cm} cm`,selected.comprimento_cm&&`Comprimento: ${selected.comprimento_cm} cm`,selected.peso_g&&`Peso: ${selected.peso_g} g`,selected.volume_ml&&`Volume: ${selected.volume_ml} ml`].filter(Boolean).join(' · ')}</p></>}{selected.ingredientes&&<p><b>Ingredientes:</b> {selected.ingredientes}</p>}{selected.alergenos&&<p><b>Alérgenos:</b> {selected.alergenos}</p>}</div></article></div>}
 </div>
}
createRoot(document.getElementById('root')!).render(<App/>);
